export const MenuItems=[
    {
       id:1,
       title:"Anasayfa",
       url:"#",
       cName:"active",
       subMenuItems:[
          {
            title1:"Home1",
            url1:"#",
            cName1:"menu-sub-items",
          },
       ]
    },
    {
      id:2,
      title:"About",
      url:"#",
      cName:"menu-items",
      subMenuItems:[
         {
           title1:"About1",
           url1:"#",
           cName1:"menu-sub-items",
         },
         {
            title1:"About2",
            url1:"#",
            cName1:"menu-sub-items",
          },
      ]
   },
    {
        id:3,
        title:"Services",
        url:"#",
        cName:"menu-items",
        subMenuItems:[
         {
           title1:"Services1",
           url1:"#",
           cName1:"menu-sub-items",
         },
         {
          title1:"Services2",
          url1:"#",
          cName1:"menu-sub-items",
        },
      ]
     },
     {
        id:4,
        title:"Products",
        url:"#",
        cName:"menu-items",
        subMenuItems:[
         {
           title1:"Products1",
           url1:"#",
           cName1:"menu-sub-items",
         },
         {
          title1:"Products2",
          url1:"#",
          cName1:"menu-sub-items",
        },
        {
          title1:"Products3",
          url1:"#",
          cName1:"menu-sub-items",
        },
      ]
     },
     {
        id:5,
        title:"Contact",
        url:"#",
        cName:"menu-items",
        subMenuItems:[
         {
           title1:"Contact1",
           url1:"#",
           cName1:"menu-sub-items",
         },
      ]
     },  
]
export default MenuItems